let descs = {
    "stone": "It's just stone. What did you expect? Just a solid hunk of rock, nothing special. (Designed by Samuel Green)",
    "voidElement": "Wat",
    "copper": "A useful but common ore found all over the mine. Please don't ignore it, minerals have feelings too. (Designed by Samuel Green)",
    "coal": "Dead dino. The question is, what killed the dinos? Was it caused by global warming from the burning of fossil fuels? (Designed by Samuel Green)",
    "iron": "Iron was often considered to be uncommon, until people got common sense. Then they lost it again. The cycle of life. (Designed by Samuel Green)",
    "lead": "Lead is a slightly rarer material used in ancient pipes, but deadly poisonous. I would love my water to be poisoned! Fun! (Idea by anonymous, designed by Samuel Green)",
    "amethyst": "Shiny crystal. OoooOoOOoOoOoOooOoOoOOoO",
    "basalt": "Basalt has been found containing rare ores inside of it, but many of these rare ores have been found before basalt started appearing independently. I'm confused. (Idea by Samuel Green)",
    "magma": "Magma is molten rock. What did you do to Dwayne? YOU CAN BE IMPRISONED FOR 20 YEARS FOR TORTURE!!! I'm calling the police right now, you're lucky I don't have pepper spray on me. (Designed by Samuel Green)",
    "gold": "Gold is a precious metal that everyone wants because it looks cool. Unless it's a Minecraft gold block house. Unless you're 5. (Designed by Samuel Green)",
    "relic": "This bronze relic is from 2,500 years ago during a time of prosperity. Don't ask why it's fully in tact, we don't know why it is either.",
    "emerald": "Emeralds were once considered one of the rarest ores in the mine, until people gained the courage to dig deeper. Many rarer ores were found including the writings of the myths of the Unseens. The descriptions should be silly why did I add lore ihuvbfiuhdf (disignd by ges who)",
    "diamond": "Muijnecraft????? (Designed by Samuel Green)",
    "fossil": "Remember when we said coal was dead dino? This must be a dino put in an eternal fate of suffering. Wait, I know what killed the dinos! It was capitalism, look at the oil! (Idea by Samuel Green)",
    "painite": "Red, rare, reveres alliteration, really just cooler than rubies, why am i doing alliteration? What are rubies? They aren't in this mine! (Designed by Samuel Green)",
    "vyvyxyn": "Vyvyxyn is a colorful ore representing the six colors of rainbow due to its formation from prismatic crystals. Yes, there are 6 colors, fun fact Issac Newton added indigo because he wanted them to be 7 colors for good luck. (Designed by Samuel Green)",
    "xyxyvylyn": "Xyxyvylyn is a dark counterpart of Vyvyxyn. Sometimes it is grinded into a very expensive and spicy salt and used in trace amounts to give extra spice to meals. Eating too much can make you act edgy or like a Roblox roleplayer. (Designed by Samuel Green)",
    "chilledamethyst": "The Chilled Amethyst is an amethyst transformed by extreme pressure and cold. The improbable conditions of it forming in an average climate make it only findable at night. It used to be used to make refrigerators colder but multiple lawsuits were filed of people dying of hypothermia. (Designed by Samuel Green)",
    "infernalgold": "Infernal Gold is gold transformed by extreme pressure and heat. The improbable conditions of it forming in an average climate make it only findable at day. Nobody knows if the gold nuggets on the top are actually real ore. (Designed by Samuel Green)",
    "cobalt": "You're only alive because of video game logic. Run.",
    "patricine": "[EVENT ORE] Patricine is said to make anyone who gets near it lucky. Over time its effects seem have to been deteriorating, but it is still actively giving miners near it some better luck.",
    "crysor": "Crysor is a very cold material. Apparently dogs like to lick it for some reason. We think the reason is because it feels good on their snoot. (Idea, design, and description by Samuel Green)",
    "porvileon": "Porvileon sends objects who touch it into another dimension. Nobody knows where it goes because humans can't fit through it. Many theories have sparked of where it goes. Some notable ones are The End, planet Y78aÆg.j, or to the 4th dimension. (Idea and design by Samuel Green)",
    "mysalin": "Mysalin is a funky ore. Contrary to popular belief, it is actually a crystal. It formed during a volcano and blizzard at the same time, causing it to be StrAnGe lol xd. It is completely offcentered contrary to the perfectionist beauty of other crystals.",
    "crystalresonance": "The Crystal of Resonance. Cool &#128077;",
    "astralcrystal": "The Astral Crystal gets a placeholder description. (Idea and design by Samuel Green)",
    "divinecrystal": "The Divine Crystal is one of the rarest ores ever discovered. It is known for its (literally) blinding lights from the power of the sun. Rumor has it that the only thing brighter than it is Discord light mode. The beams from the side of the core provides all of this energy. (Idea and design by Samuel Green)",

    "thefunny": "HEHEHEHEHEHEHE",
    "mrbeastore": "rumor hase it this ore gives you 1000000000000 gold and 999 iron"
}
