let descs = {
    "stone": "It's just stone. What did you expect? Just a solid hunk of rock, nothing special. (Designed by Samuel Green)",
    "voidElement": "Wat",
    "copper": "A useful but common ore found all over the mine. Please don't ignore it, minerals have feelings too. (Designed by Samuel Green)",
    "coal": "Dead dino. The question is, what killed the dinos? Was it caused by global warming from the burning of fossil fuels? (Designed by Samuel Green)",
    "iron": "Iron was often considered to be uncommon, until people got common sense. Then they lost it again. The cycle of life. (Designed by Samuel Green)",
    "lead": "Lead is a slightly rarer material used in bullets, rat posion, and ancient sewer pipes. Fun! (Idea by anonymous, designed by Samuel Green)",
    "amethyst": "Shiny crystal. OoooOoOOoOoOoOooOoOoOOoO",
    "gold": "Gold is a precious metal that everyone wants because it looks cool. Unless it's a Minecraft gold block house. Unless you're 5. (Designed by Samuel Green)",
    "relic": "This bronze relic is from 2,500 years ago during a time of prosperity. Don't ask why it's fully in tact, we don't know why it is either.",
    "emerald": "Emeralds were once considered one of the rarest ores in the mine, until people gained the courage to dig deeper. Many rarer ores were found including the writings of the myths of the Unseens. The descriptions should be silly why did I add lore ihuvbfiuhdf (disignd by ges who)",
    "diamond": "Muijnecraft????? (Designed by Samuel Green)",
    "fossil": "Remember when we said coal was dead dino? This must be a dino put in an eternal fate of suffering. Wait, I know what killed the dinos! It was capitalism, look at the oil! (Idea by Samuel Green)",
    "painite": "Red, rare, reveres alliteration, really just cooler than rubies, why am i doing alliteration? What are rubies? They aren't in this mine! (Designed by Samuel Green)",
    "vyvyxyn": "Vyvyxyn is a colorful ore representing the six colors of rainbow due to its formation from prismatic crystals. Yes, there are 6 colors, fun fact Issac Newton added indigo because he wanted them to be 7 colors for good luck. (Designed by Samuel Green)",
    "xyxyvylyn": "Xyxyvylyn is an ore. this is temporary description",
    "crysor": "Crysor is a very cold material. Apparently dogs like to lick it for some reason. We think the reason is because it feels good on their snoot. (Idea, design, and description by Samuel Green)",
    "porvileon": "Porvileon sends objects who touch it into another dimension. Nobody knows where it goes because humans can't fit through it. Many theories have sparked of where it goes. Some notable ones are The End, planet Y78aÆg.j, or to the 4th dimension. (Idea and design by Samuel Green)",
    "crystalresonance": "The Crystal of Resonance. Cool &#128077;"
}
